layout_spectrum: 0.4340474
typography_spectrum: 0.6538184
color:
  saturation: 0.7585561
  lightness: 0.959915
  brandStrength: 0.5804043
  rhythmicContrast: 0.7810563
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: 'WhiskySkills '
