name: 'WhiskySkills '
favicon: null
layout_spectrum: 0.88283
typography_spectrum: 0.6538184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5804043
  lightness: 0.959915
  saturation: 0.7585561
  rhythmicContrast: 0.7810563
purpose: []
